### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by Tobaloidee** [GabriM97/CryptoWolf#2]
Hi @ausilianapoli  I will work on the logo design now..will post here the draft! - Tobaloidee

**Comment by Tobaloidee** [comment]
Here it is @ausilianapoli  I hope you like it!
![CRYPTOWOLF pres-01](https://user-images.githubusercontent.com/36028424/55289635-63eec580-53fb-11e9-9998-ffdfe3c99bfc.png)

**Comment by ausilianapoli** [comment]
We would like to change the font because we prefer a font style similar to bitcoin: specifically the 'C' and the 'W' as the 'B' of bitcoin.
Moreover, how will the logo become if you replace the wolf's eyes with the bitcoin symbol?

**Comment by Tobaloidee** [comment]
here's what it looks like in 2 versions
![CRYPTOWOLF pres 2-02-02](https://user-images.githubusercontent.com/36028424/55307752-0ace7280-548b-11e9-9bef-e39594431ef6.png)

**Comment by Tobaloidee** [comment]
I am just not sure if we can use the "B" bitcoin logo into the design because of its copyright? I'm not sure

**Comment by ausilianapoli** [comment]
Ok, so we discard bitcoin eyes version.
Could we view logo version without linear regression line, please?
In addition, is there a font more 'cyber'?

**Comment by Tobaloidee** [comment]
I edited the design and added stripes to the outer circle to make more like a coin..I also made the wolf head larger and fixed the eye shape...also I applied fonts to choose from
![CRYPTOWOLF new pres-02](https://user-images.githubusercontent.com/36028424/55369611-d8c01d80-5529-11e9-8226-59e969ba9a1f.png)
![CRYPTOWOLF new pres-03](https://user-images.githubusercontent.com/36028424/55369616-dcec3b00-5529-11e9-81ba-abd9aca6ade8.png)

**Comment by ausilianapoli** [comment]
Could you make the last versions without the back stripes to the outer circle, please?

**Comment by Tobaloidee** [comment]
here, I forgot my laptop at work where I saved my raw files..I just edited this in PS..
![1](https://user-images.githubusercontent.com/36028424/55409825-50776200-5595-11e9-967d-59e586a2d2e6.png)
![2](https://user-images.githubusercontent.com/36028424/55409837-553c1600-5595-11e9-9997-d8e0dcffb960.png)

**Comment by Tobaloidee** [comment]
what do you think @ausilianapoli ?

**Comment by ausilianapoli** [comment]
We choose the first logo of the last sequence without coin symbol! :smiley:

**Comment by Tobaloidee** [comment]
This one @ausilianapoli ?
![this one-01](https://user-images.githubusercontent.com/36028424/55525183-aeee2e80-56c2-11e9-8f32-93ea10e74a8a.png)

will finalize it and make a PR later this day 💯

**Comment by ausilianapoli** [comment]
Exactly!

**Comment by Tobaloidee** [comment]
here's the PR #3 with the new logo and readme update @ausilianapoli  and also you can download different versions and file formats on this [LINK](https://drive.google.com/drive/u/1/folders/1l7ibeJx_TO0Y_fa9ZKY2xW8M4YOUgbr4) to my drive.

Thank you and My best regards to the project! 
-Tobaloidee

*I'm just a mention away if you need my help in the future logos

**Comment by Tobaloidee** [comment]
Thanks for accepting my contribution! 👍

**Comment by ausilianapoli** [comment]
Thanks for your interesting contribution! If we want future logos, we will need your help! :smile: 
We add our acknowledgments for you in the README. Thanks a lot!

**Comment by Tobaloidee** [comment]
I will gladly make a logo for you in the future! Best regards!!
